#!/usr/bin/env python3
import time
import logging
import subprocess
import sys
from pathlib import Path
from datetime import datetime

logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
    handlers=[
        logging.FileHandler(Path(__file__).parent.parent / 'scheduler.log'),
        logging.StreamHandler()
    ]
)
logger = logging.getLogger('Scheduler')

class TaskScheduler:
    def __init__(self, vault_path: str):
        self.vault_path = Path(vault_path)
        self.briefings_dir = self.vault_path / 'Briefings'
        self.signals_dir = self.vault_path / 'Signals'
        self.briefings_dir.mkdir(exist_ok=True)
        self.signals_dir.mkdir(exist_ok=True)
        self.running = True

    def daily_briefing(self):
        date_str = datetime.now().strftime('%Y-%m-%d')
        briefing = f'''---
generated: {datetime.now().isoformat()}
period: {date_str}
type: daily_briefing
---

# Daily Briefing - {date_str}

## Executive Summary
Good morning! Here is your AI Employee's daily briefing.

## Pending Items
Total items in Needs_Action: {len(list((self.vault_path / 'Needs_Action').glob('*.md'))) if (self.vault_path / 'Needs_Action').exists() else 0}
Pending approvals: {len(list((self.vault_path / 'Pending_Approval').glob('*.md'))) if (self.vault_path / 'Pending_Approval').exists() else 0}

## Scheduled Tasks Today
- [ ] Process new emails
- [ ] Check for urgent messages
- [ ] Review pending approvals
- [ ] Post business updates

---
*Generated by AI Employee Silver Tier*
'''
        briefing_file = self.briefings_dir / f'{date_str}_Daily_Briefing.md'
        briefing_file.write_text(briefing)
        signal_file = self.signals_dir / 'daily_briefing.md'
        signal_file.write_text(f'New daily briefing available: {briefing_file.name}')
        logger.info(f'Daily briefing created: {briefing_file.name}')

    def weekly_audit(self):
        date_str = datetime.now().strftime('%Y-%m-%d')
        audit = f'''---
generated: {datetime.now().isoformat()}
period: weekly
type: business_audit
---

# Weekly Business Audit - Week of {date_str}

## Revenue Summary
- Total earned this week: Pending calculation
- Invoices sent: Pending count
- Payments received: Pending count

## Completed Tasks
- Review Done folder for weekly completed items

## Bottlenecks & Improvements
- Identify any recurring delays
- Review watcher performance
- Check for failed operations

## Proactive Suggestions
- Review software subscriptions
- Check for unpaid invoices
- Plan next week's priorities

---
*Generated by AI Employee Silver Tier*
'''
        audit_file = self.briefings_dir / f'{date_str}_Weekly_Audit.md'
        audit_file.write_text(audit)
        logger.info(f'Weekly audit created: {audit_file.name}')

    def run_scheduled(self):
        logger.info('Task Scheduler started')
        last_daily = None
        last_weekly = None

        while self.running:
            now = datetime.now()
            today = now.strftime('%Y-%m-%d')
            week_num = now.isocalendar()[1]

            if last_daily != today and now.hour == 8 and now.minute == 0:
                self.daily_briefing()
                last_daily = today

            if last_weekly != week_num and now.weekday() == 6 and now.hour == 20 and now.minute == 0:
                self.weekly_audit()
                last_weekly = week_num

            time.sleep(30)

    def create_windows_task(self):
        script_path = Path(__file__).absolute()
        task_name = 'AIEmployeeOrchestrator'
        action = f'python "{script_path}"'
        trigger = '@daily'
        cmd = f'schtasks /Create /TN "{task_name}" /TR "{action}" /SC DAILY /ST 08:00 /F'
        try:
            subprocess.run(cmd, shell=True, check=True)
            logger.info(f'Windows Task "{task_name}" created')
        except subprocess.CalledProcessError as e:
            logger.error(f'Failed to create Windows Task: {e}')

if __name__ == '__main__':
    vault = Path(__file__).parent.parent.absolute()
    scheduler = TaskScheduler(str(vault))
    if len(sys.argv) > 1 and sys.argv[1] == '--create-task':
        scheduler.create_windows_task()
    else:
        scheduler.run_scheduled()
